# Generated by Django 4.2.1 on 2023-09-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='age',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
