# Generated by Django 4.2.1 on 2023-09-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_candidate_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
