# Generated by Django 4.2.1 on 2023-09-03 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_candidate_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='job',
            field=models.CharField(default=datetime.datetime(2023, 9, 3, 9, 53, 8, 61795, tzinfo=datetime.timezone.utc), max_length=5),
            preserve_default=False,
        ),
    ]
