# Generated by Django 4.2.1 on 2023-09-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_candidate_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
