# Generated by Django 4.2.1 on 2023-09-04 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_candidate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.FileField(default=datetime.datetime(2023, 9, 4, 7, 55, 47, 531432, tzinfo=datetime.timezone.utc), upload_to='candidate_photo'),
            preserve_default=False,
        ),
    ]
